<?php

return [
    'brand' => 'Bay Area Epoxy Wholesale',
    'legal_name' => 'Bayarea Epoxy wholesale',
    'phone' => '+1 (510) 362-8501',
    'phone_href' => '+15103628501',
    'whatsapp_number' => '15103628501',
    'address' => '2495 American Ave, Hayward, CA 94545',
    'email' => 'sales@bayareaepoxywholesale.com',
    'tracking' => [
        'ga4_id' => 'G-Q9S4X8JF0G',
        'google_ads_id' => 'AW-16807597345',
        'google_tag_id' => 'GT-PZQ32G67',
        'gtm_id' => null,
        'meta_pixel_id' => '4169018560018328',
        'facebook_domain_verification' => 'jo54eqlwaowmnoko65500o18rt9c7q',
        'google_site_verifications' => [
            '4ZTW1BxrxnK0aIKjYYBe5YYtXSE23ByazldrOaKSr40',
            'eCJPL3f685Gl2lc2zwo3ue15zaYHMA4l9iikSvIlYVI',
        ],
        'ahrefs_site_verification' => '356c2c9e7e55bbfcb9626aa5f12a10d320ac4a3942467974d6fc3587ce11e14a',
    ],
    'hero_image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/BlueLabel.jpg?v=1746812312',
    'logo_image' => 'https://bayareaepoxywholesale.com/cdn/shop/files/logofg_344x250.png?v=1696317287',
    'products' => [
        [
            'slug' => 'crown-polymers-blue-label-epoxy-100-3-gallons-clear',
            'title' => 'Crown Polymers Blue Label Epoxy 100 3 Gallons Clear',
            'category' => 'Epoxy Floor Coatings',
            'tags' => ['Epoxy', '100% solids', 'Base coat'],
            'price' => 300,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/BlueLabel.jpg?v=1746812312',
            'summary' => 'High-performance two-component epoxy with strong abrasion and chemical resistance for base coats, metallic coats, and top coats.',
            'details' => ['100% solids epoxy', 'Low viscosity and low odor', 'VOC compliant in North America', 'Glossy self-leveling finish'],
        ],
        [
            'slug' => 'crown-polymers-blue-label-polyaspartic-100-3-gallons-clear',
            'title' => 'Crown Polymers Blue Label Polyaspartic 100 3 Gallons Clear',
            'category' => 'Protective Coatings',
            'tags' => ['Polyaspartic', 'Topcoat', 'Clear'],
            'price' => 285,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/blue_label_Poly.jpg?v=1746817730',
            'summary' => 'High-solids clear topcoat built for abrasion, chemical, and stain resistance with strong gloss retention.',
            'details' => ['Two-component clear topcoat', 'Excellent abrasion resistance', 'Good impact resistance', 'Low VOC options available'],
        ],
        [
            'slug' => 'crown-polymers-blue-label-epoxy-100-3-gallons-clear-copy',
            'title' => '8110 CrownSeal CRU UV Stable 1.5 Gallon Kit Urethane Top Coat',
            'category' => 'Protective Coatings',
            'tags' => ['Urethane', 'UV stable', 'Finish coat'],
            'price' => 204.48,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/Crown_Polymers_8110_A-600x495.jpg?v=1746818243',
            'summary' => 'Abrasion, chemical, and stain-resistant aliphatic polyester polyurethane finish coat for clear gloss or clear satin systems.',
            'details' => ['UV-stable urethane finish', 'Clear gloss and satin options', 'Chemical and stain resistant', 'Professional finish coat'],
        ],
        [
            'slug' => '8312-crowncove™-high-build-thixotropic-epoxy',
            'title' => '8312 CrownCove - High-Build Thixotropic Epoxy',
            'category' => 'Cove Base',
            'tags' => ['Cove', 'Epoxy', 'Vertical application'],
            'price' => 285,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/Crown_Polymers_8312_A-600x495.jpg?v=1746826378',
            'summary' => 'Clear two-component thixotropic epoxy formulated for vertical cove base applications where sag resistance matters.',
            'details' => ['100% solids thermosetting epoxy', 'Hand-trowel applied', 'Designed for 4 inch and 6 inch cove', 'Strong sag resistance'],
        ],
        [
            'slug' => 'premera-t2-mcm-1-gallon',
            'title' => 'Premera T2 MCM 1 Gallon',
            'category' => 'Protective Coatings',
            'tags' => ['Topcoat', 'Concrete protection', 'Single component'],
            'price' => 165,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/premeraT2.jpg?v=1746826743',
            'summary' => 'Single-component clear coating for concrete, terrazzo, tile, and existing coating protection.',
            'details' => ['Spray-down sol-gel coating', 'Quartz mineral barrier', 'No backroll workflow', 'Clear protective finish'],
        ],
        [
            'slug' => 'wooster-br045-18-big-ben-roller-frame',
            'title' => 'Wooster BR045 18" Big Ben Roller Frame',
            'category' => 'Accessories',
            'tags' => ['Tools', 'Roller frame'],
            'price' => 39.99,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/071497134356.jpg?v=1746827459',
            'summary' => 'Lightweight 18 inch roller frame for professional coating installation.',
            'details' => ['Fits 18 inch roller covers', 'Lightweight polypropylene construction', 'Sherlock GT compatible', 'No tools required'],
        ],
        [
            'slug' => '18-speedsqueegee®-flat-stiff',
            'title' => '18" SpeedSqueegee Seymour Midwest',
            'category' => 'Accessories',
            'tags' => ['Tools', 'Squeegee'],
            'price' => 39.99,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/speedsqueegeeproductbrochure_2020_1.jpg?v=1747242051',
            'summary' => 'Flat stiff SpeedSqueegee for coating placement and controlled application rates.',
            'details' => ['Flat stiff blade option', 'Used for coating placement', 'Compatible with professional floor systems', 'Multiple notch rates available'],
        ],
        [
            'slug' => '1-4-40-lbs-flakes-box',
            'title' => '1/4" 40 lbs Flakes Box',
            'category' => 'Flakes',
            'tags' => ['Epoxy', 'Flakes', 'Broadcast media'],
            'price' => 120,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/1.jpg?v=1747166303',
            'summary' => 'Decorative epoxy flakes for durable, slip-resistant, and visually consistent floor systems.',
            'details' => ['40 lb box', 'Adds texture and color', 'Improves slip resistance', 'Common for garages, showrooms, and warehouses'],
        ],
        [
            'slug' => 'crown-polymers-8320-crownshield-all-n-one-epoxy',
            'title' => '8320 CrownShield All-n-One Epoxy 3 Gallon Clear',
            'category' => 'Epoxy Floor Coatings',
            'tags' => ['Epoxy', 'Hybrid', 'Chemical resistance'],
            'price' => 289.50,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/Crown_Polymers_8320_A-1-600x495.jpg?v=1747241308',
            'summary' => 'Hybrid Bis F and Bis A two-component epoxy for challenging environments requiring abrasion and chemical resistance.',
            'details' => ['100% solids hybrid epoxy', 'Low viscosity and low odor', 'Abrasion and chemical resistant', 'Multi-functional system component'],
        ],
        [
            'slug' => 'vantage-roller-cover-18-in-3-8-nap',
            'title' => 'Vantage Roller Cover | 18 in 3/8 Nap',
            'category' => 'Accessories',
            'tags' => ['Tools', 'Roller cover'],
            'price' => 9.99,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/GM-939M.webp?v=1747242423',
            'summary' => 'Industrial roller cover for coating floors with a professional 3/8 inch nap.',
            'details' => ['18 inch roller cover', '3/8 inch nap', 'Industrial coating use', 'Available individually or by box'],
        ],
        [
            'slug' => 'epoxy-resin-solid-epoxy-pigments',
            'title' => 'Pigments IN STOCK White | Medium Gray | Black | Epoxy Pigments',
            'category' => 'Metallic Pigments',
            'tags' => ['Pigment', 'Epoxy color', 'In stock'],
            'price' => null,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/white_color_pigment.jpg?v=1747250508',
            'summary' => 'Standard epoxy colors and safety pigments for pigmented base coats in decorative coating systems.',
            'details' => ['White, medium gray, and black options', 'Used in base coats', 'Supports flake and metallic systems', 'In-stock color program'],
        ],
        [
            'slug' => '810-crowncrete-u-skim-coat',
            'title' => '810 CrownCrete U Skim Coat',
            'category' => 'Urethane Cement',
            'tags' => ['Urethane cement', 'Skim coat'],
            'price' => null,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/810partb.jpg?v=1747257536',
            'summary' => 'Three-part urethane polymer concrete high-build coating for thin film roll-applied concrete resurfacing.',
            'details' => ['Three-part urethane polymer concrete', 'Thin film roll-applied system', 'Concrete protection flooring product', 'Quote required for project pricing'],
        ],
        [
            'slug' => '814-crowncrete-u-1-4',
            'title' => '814 CrownCrete U 1/4',
            'category' => 'Urethane Cement',
            'tags' => ['Urethane cement', 'Self-leveling'],
            'price' => null,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/814.jpg?v=1747260771',
            'summary' => 'Self-leveling urethane-cement mortar designed to protect concrete from abrasion, chemicals, impact, and temperature cycling.',
            'details' => ['Three-component flowable overlayment', '1/4 inch system profile', 'Handles thermal cycling', 'Industrial concrete protection'],
        ],
        [
            'slug' => '818-crowncrete-u-1-8',
            'title' => '818 CrownCrete U 1/8',
            'category' => 'Urethane Cement',
            'tags' => ['Urethane cement', 'Self-leveling'],
            'price' => null,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/818B.jpg?v=1747261029',
            'summary' => 'Self-leveling urethane cement overlayment for industrial floors exposed to impact, abrasion, and chemicals.',
            'details' => ['Three-component flowable system', '1/8 inch system profile', 'Industrial floor resurfacing', 'Project quote required'],
        ],
        [
            'slug' => '838-crowncrete-u-3-8-trowel-grade',
            'title' => '838 CrownCrete U 3/8 Trowel Grade',
            'category' => 'Urethane Cement',
            'tags' => ['Urethane cement', 'Trowel grade'],
            'price' => null,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/838.jpg?v=1747261088',
            'summary' => 'Heavy-duty high-density trowel-grade urethane polymer concrete system for demanding floor environments.',
            'details' => ['Three-part trowel-grade product', '3/8 inch heavy-duty system', 'High-density packed mortar', 'Built for demanding industrial floors'],
        ],
        [
            'slug' => 'metallic-pigments',
            'title' => 'Metallic Pigments',
            'category' => 'Metallic Pigments',
            'tags' => ['Metallic', 'Pigment'],
            'price' => 30,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/8.png?v=1747427205',
            'summary' => 'Metallic pigment options for high-gloss decorative epoxy floors with depth and movement.',
            'details' => ['Decorative metallic finish', 'Used with clear epoxy systems', 'Creates depth and visual movement', 'Multiple color options'],
        ],
        [
            'slug' => 'metallic-epoxy-100-lv-3-gallon-clear',
            'title' => 'Metallic Epoxy 100 LV 3 gallon Clear',
            'category' => 'Epoxy Floor Coatings',
            'tags' => ['Metallic epoxy', 'Clear epoxy'],
            'price' => 150,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/blue_label_epoxy.jpg?v=1746817187',
            'summary' => 'Clear low-viscosity epoxy for metallic floor systems and decorative high-gloss applications.',
            'details' => ['Clear LV epoxy', 'Made for metallic systems', 'High-gloss decorative finish', 'Pairs with metallic pigment packs'],
        ],
    ],
    'collections' => [
        'epoxy-for-concrete-floors' => [
            'title' => 'Epoxy For Concrete Floors',
            'summary' => 'High-performance epoxy floor coatings, pigments, flakes, and clear systems for residential, commercial, and industrial concrete.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/BlueLabel.jpg?v=1746812312',
            'products' => ['crown-polymers-blue-label-epoxy-100-3-gallons-clear', 'crown-polymers-8320-crownshield-all-n-one-epoxy', 'metallic-epoxy-100-lv-3-gallon-clear', 'epoxy-resin-solid-epoxy-pigments', '1-4-40-lbs-flakes-box'],
        ],
        'protective-coat' => [
            'title' => 'Protective Coatings',
            'summary' => 'Clear topcoats and protective finishes for abrasion resistance, stain resistance, UV stability, and long-term gloss retention.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/premeraT2.jpg?v=1746826743',
            'products' => ['crown-polymers-blue-label-polyaspartic-100-3-gallons-clear', 'crown-polymers-blue-label-epoxy-100-3-gallons-clear-copy', 'premera-t2-mcm-1-gallon'],
        ],
        'cove-base' => [
            'title' => 'Cove Base',
            'summary' => 'High-build cove base epoxy for vertical transitions, sanitary details, and industrial floor-wall interfaces.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/Crown_Polymers_8312_A-600x495.jpg?v=1746826378',
            'products' => ['8312-crowncove™-high-build-thixotropic-epoxy'],
        ],
        'accessories' => [
            'title' => 'Accessories',
            'summary' => 'Professional rollers, squeegees, and installation tools for coating crews.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/speedsqueegeeproductbrochure_2020_1.jpg?v=1747242051',
            'products' => ['wooster-br045-18-big-ben-roller-frame', '18-speedsqueegee®-flat-stiff', 'vantage-roller-cover-18-in-3-8-nap'],
        ],
        'flakes' => [
            'title' => 'Flakes',
            'summary' => 'Decorative broadcast flakes for texture, durability, and slip-resistant epoxy flooring systems.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/1.jpg?v=1747166303',
            'products' => ['1-4-40-lbs-flakes-box'],
        ],
        'urethane-cement' => [
            'title' => 'Urethane Cement',
            'summary' => 'CrownCrete U urethane cement systems for industrial kitchens, breweries, manufacturing, and heavy service concrete.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/814.jpg?v=1747260771',
            'products' => ['810-crowncrete-u-skim-coat', '814-crowncrete-u-1-4', '818-crowncrete-u-1-8', '838-crowncrete-u-3-8-trowel-grade'],
        ],
        'metallic-colors' => [
            'title' => 'Metallic Colors',
            'summary' => 'Metallic pigment systems and clear epoxy for decorative floors with a polished, high-gloss finish.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/8.png?v=1747427205',
            'products' => ['metallic-pigments', 'metallic-epoxy-100-lv-3-gallon-clear'],
        ],
    ],
    'pages' => [
        'contact' => [
            'title' => 'Contact',
            'summary' => 'Talk to a Bay Area epoxy and waterproofing supply specialist.',
            'sections' => [
                ['title' => 'Hayward Warehouse', 'body' => 'Visit or contact the team at 2495 American Ave, Hayward, CA 94545 for product availability, job quoting, and contractor supply support.'],
                ['title' => 'Fastest Response', 'body' => 'Call, text, or WhatsApp the team for product recommendations, order planning, and pickup coordination.'],
            ],
        ],
        'about-us' => [
            'title' => 'About Us',
            'summary' => 'Industrial epoxy, waterproofing, and concrete coating supplies for contractors across the Bay Area and California.',
            'sections' => [
                ['title' => 'Wholesale Focus', 'body' => 'The site is being rebuilt around contractor enquiries, technical product selection, and local supply support instead of a generic ecommerce checkout.'],
                ['title' => 'Product Systems', 'body' => 'We organize materials by flooring system so crews can quickly compare epoxy, urethane cement, flakes, pigments, topcoats, and waterproofing options.'],
            ],
        ],
        'epoxy-calculator' => [
            'title' => 'Epoxy Calculator',
            'summary' => 'Estimate material needs for epoxy coating systems before requesting a final quote.',
            'sections' => [
                ['title' => 'Coverage Planning', 'body' => 'Share square footage, concrete condition, target system, and desired build thickness so we can confirm gallons, flakes, tools, and topcoat needs.'],
                ['title' => 'Quote Support', 'body' => 'Calculator outputs should be treated as planning estimates. Final coverage depends on porosity, repair work, broadcast rate, and system design.'],
            ],
        ],
        'color-chart' => [
            'title' => 'Color Chart',
            'summary' => 'Review standard pigment, flake, quartz, and metallic options for epoxy floor systems.',
            'sections' => [
                ['title' => 'Common Colors', 'body' => 'White, medium gray, black, metallic pigments, and decorative flake blends are organized for fast contractor selection.'],
                ['title' => 'Sample Matching', 'body' => 'For project-critical colors, confirm samples and batch availability with the warehouse before installation.'],
            ],
        ],
        'brochures-resources' => [
            'title' => 'Brochures Resources',
            'summary' => 'Technical resources, product literature, and specification support for coating crews.',
            'sections' => [
                ['title' => 'Product Literature', 'body' => 'Use this section for data sheets, brochures, installation notes, and brand documentation as the new catalog is expanded.'],
                ['title' => 'Specification Help', 'body' => 'Send project conditions through WhatsApp and the team can help identify the right primer, body coat, broadcast, and finish coat.'],
            ],
        ],
        'training-quick-tips' => [
            'title' => 'Training Quick Tips',
            'summary' => 'Practical tips for epoxy, urethane cement, waterproofing, and decorative concrete coating installation.',
            'sections' => [
                ['title' => 'Crew-Oriented Guidance', 'body' => 'Training content will focus on surface prep, mixing, coverage, working time, broadcast technique, and topcoat selection.'],
                ['title' => 'Local Support', 'body' => 'Contractors can contact the Hayward team for job-specific recommendations before mobilizing crews.'],
            ],
        ],
        'training-schedule' => [
            'title' => 'Training Schedule',
            'summary' => 'Upcoming product training and contractor education events.',
            'sections' => [
                ['title' => 'Request Schedule', 'body' => 'Use WhatsApp to ask about upcoming hands-on trainings, product demos, and manufacturer sessions.'],
                ['title' => 'Topics', 'body' => 'Epoxy flakes, metallic epoxy, urethane cement, waterproof deck systems, prep standards, and topcoat workflows.'],
            ],
        ],
        'urethane-cement' => [
            'title' => 'Urethane Cement',
            'summary' => 'Heavy-duty urethane cement systems for industrial concrete floors exposed to thermal shock, chemicals, and impact.',
            'sections' => [
                ['title' => 'Industrial Protection', 'body' => 'CrownCrete U systems cover skim coat, self-leveling, and trowel-grade profiles for kitchens, manufacturing, breweries, and processing spaces.'],
                ['title' => 'Project Selection', 'body' => 'System choice depends on traffic, temperature, cleaning chemicals, substrate condition, and target thickness.'],
            ],
        ],
        'esd-static-dissipative-conductive' => [
            'title' => 'ESD Static Dissipative Conductive',
            'summary' => 'ESD and conductive flooring system support for technical environments.',
            'sections' => [
                ['title' => 'Controlled Flooring', 'body' => 'Use this page to position conductive and static dissipative coating systems for labs, electronics, production, and controlled spaces.'],
                ['title' => 'Technical Confirmation', 'body' => 'ESD systems should be quoted with performance requirements, substrate details, grounding design, and maintenance expectations.'],
            ],
        ],
        'epoxy-supplier-california' => [
            'title' => 'Epoxy Supplier California',
            'summary' => 'Wholesale epoxy flooring supplies and waterproofing products serving Hayward, the Bay Area, and California contractors.',
            'sections' => [
                ['title' => 'California Supply', 'body' => 'Contractors can source epoxy, polyaspartic, urethane cement, flakes, pigments, and tools through the Hayward warehouse.'],
                ['title' => 'Professional Support', 'body' => 'The new site is designed around fast product selection, direct enquiry, and technical support instead of a Shopify cart.'],
            ],
        ],
    ],
    'posts' => [
        [
            'blog' => 'news',
            'slug' => 'epoxy-concrete-coatings-the-ideal-solution-for-food-beverage-manufacturing',
            'title' => 'Epoxy Concrete Coatings: The Ideal Solution for Food & Beverage Manufacturing',
            'date' => '2025-01-14',
            'summary' => 'How epoxy coating systems support cleanability, durability, and chemical resistance in food and beverage facilities.',
        ],
        [
            'blog' => 'news',
            'slug' => 'epoxy-flooring-solutions-for-wineries-strength-durability-and-aesthetic-excellence',
            'title' => 'Epoxy Flooring Solutions for Wineries: Strength, Durability, and Aesthetic Excellence',
            'date' => '2025-01-22',
            'summary' => 'Flooring considerations for wineries balancing durability, cleanability, and a polished guest-facing finish.',
        ],
        [
            'blog' => 'news',
            'slug' => 'why-removing-gypsum-flooring-is-essential-for-durable-and-long-lasting-results-for-metallic-floor-epoxy-floors-and-urethane-cement-floors',
            'title' => 'Why Removing Gypsum Flooring Is Essential for Durable and Long-Lasting Results',
            'date' => '2025-02-05',
            'summary' => 'Why substrate removal and preparation matter before metallic epoxy and urethane cement installations.',
        ],
        [
            'blog' => 'news',
            'slug' => 'exploring-crowncrete-u-versatile-solutions-for-industrial-flooring-needs',
            'title' => 'Exploring CrownCrete U: Versatile Solutions for Industrial Flooring Needs',
            'date' => '2025-02-18',
            'summary' => 'A contractor-focused look at urethane cement profiles for demanding industrial flooring conditions.',
        ],
        [
            'blog' => 'news',
            'slug' => 'quartz-double-broadcast-system-enhance-durability-and-safety-with-the-crownquartz-db-color-quartz-system',
            'title' => 'Quartz Double Broadcast System: Enhance Durability and Safety',
            'date' => '2025-02-26',
            'summary' => 'How double broadcast quartz systems add texture, durability, and traction to resinous floors.',
        ],
        [
            'blog' => 'news',
            'slug' => 'grind-seal-concrete-with-crownseal-8112-a-reliable-solution-for-durable-and-safe-concrete-coatings',
            'title' => 'Grind & Seal Concrete with CrownSeal 8112',
            'date' => '2025-03-04',
            'summary' => 'A practical overview of grind-and-seal concrete coating workflows for durable, serviceable floors.',
        ],
        [
            'blog' => 'news',
            'slug' => 'polydeck-150-150sc-the-ultimate-waterproof-deck-system-for-long-lasting-protection',
            'title' => 'Polydeck 150: The Ultimate Waterproof Deck System for Long-Lasting Protection',
            'date' => '2025-03-11',
            'summary' => 'Waterproof deck system basics for pedestrian traffic, vehicular surfaces, and long-term protection.',
        ],
        [
            'blog' => 'news',
            'slug' => 'fp1-fusion-primer-revolutionizing-surface-preparation-for-dust-sensitive-environments',
            'title' => 'FP1 Fusion Primer: Revolutionizing Surface Preparation for Dust-Sensitive Environments',
            'date' => '2025-04-02',
            'summary' => 'Primer selection guidance for projects where dust sensitivity and surface preparation matter.',
        ],
        [
            'blog' => 'news',
            'slug' => 'epoxy-for-concrete-floors-the-ultimate-guide-to-durable-high-performance-flooring',
            'title' => 'Epoxy for Concrete Floors: The Ultimate Guide to Durable & High-Performance Flooring',
            'date' => '2026-01-03',
            'summary' => 'A broad guide to epoxy floor systems, durability, maintenance, and use cases.',
        ],
        [
            'blog' => 'news',
            'slug' => 'best-epoxy-flooring-for-warehouse-in-usa-complete-industrial-guide',
            'title' => 'Best Epoxy Flooring for Warehouse in USA: Complete Industrial Guide',
            'date' => '2026-02-10',
            'summary' => 'Warehouse flooring selection factors including traffic, abrasion, impact, cleaning, and downtime.',
        ],
        [
            'blog' => 'news',
            'slug' => 'epoxy-flooring-products-in-california',
            'title' => 'Epoxy Flooring Products in California',
            'date' => '2026-03-12',
            'summary' => 'A California-focused overview of epoxy flooring products, contractor supply, and system selection.',
        ],
        [
            'blog' => 'news',
            'slug' => 'deck-waterproofing-urethane-cement-supplier-bay-area',
            'title' => 'Deck Waterproofing & Urethane Cement Supplier Bay Area',
            'date' => '2026-04-18',
            'summary' => 'Supply support for waterproof deck coatings and urethane cement systems in the Bay Area.',
        ],
    ],
    'policies' => [
        'privacy-policy' => [
            'title' => 'Privacy Policy',
            'summary' => 'Privacy policy content will be finalized before launch. Current tracking IDs are preserved for continuity.',
        ],
        'refund-policy' => [
            'title' => 'Refund Policy',
            'summary' => 'Refund and return terms should be confirmed by the business before launch.',
        ],
        'shipping-policy' => [
            'title' => 'Shipping Policy',
            'summary' => 'Shipping, pickup, and delivery terms should be confirmed by the business before launch.',
        ],
        'terms-of-service' => [
            'title' => 'Terms of Service',
            'summary' => 'Terms of service content should be reviewed and approved before launch.',
        ],
    ],
];
