<?php

return [
    'brand' => 'Bay Area Epoxy Wholesale',
    'legal_name' => 'Bayarea Epoxy wholesale',
    'phone' => '(510) 362-8501',
    'phone_href' => '+15103628501',
    'whatsapp_number' => '15103628501',
    'address' => '2495 American Ave, Hayward, CA 94545',
    'email' => 'sales@bayareaepoxywholesale.com',
    'blog_admin_password' => env('BLOG_ADMIN_PASSWORD', 'local-blog-admin'),
    'tracking' => [
        'ga4_id' => 'G-Q9S4X8JF0G',
        'google_ads_id' => 'AW-16807597345',
        'google_tag_id' => 'GT-PZQ32G67',
        'gtm_id' => null,
        'meta_pixel_id' => '4169018560018328',
        'facebook_domain_verification' => 'jo54eqlwaowmnoko65500o18rt9c7q',
        'google_site_verifications' => [
            '4ZTW1BxrxnK0aIKjYYBe5YYtXSE23ByazldrOaKSr40',
            'eCJPL3f685Gl2lc2zwo3ue15zaYHMA4l9iikSvIlYVI',
        ],
        'ahrefs_site_verification' => '356c2c9e7e55bbfcb9626aa5f12a10d320ac4a3942467974d6fc3587ce11e14a',
    ],
    'hero_image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/BlueLabel.jpg?v=1746812312',
    'logo_image' => 'https://bayareaepoxywholesale.com/cdn/shop/files/logofg_344x250.png?v=1696317287',
    'products' => [
        [
            'slug' => 'crown-polymers-blue-label-epoxy-100-3-gallons-clear',
            'title' => 'Crown Polymers Blue Label Epoxy 100 3 Gallons Clear',
            'category' => 'Epoxy Floor Coatings',
            'tags' => ['Epoxy', '100% solids', 'Base coat'],
            'price' => 300,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/BlueLabel.jpg?v=1746812312',
            'summary' => 'High-performance two-component epoxy with strong abrasion and chemical resistance for base coats, metallic coats, and top coats.',
            'details' => ['100% solids epoxy', 'Low viscosity and low odor', 'VOC compliant in North America', 'Glossy self-leveling finish'],
        ],
        [
            'slug' => 'crown-polymers-blue-label-polyaspartic-100-3-gallons-clear',
            'title' => 'Crown Polymers Blue Label Polyaspartic 100 3 Gallons Clear',
            'category' => 'Protective Coatings',
            'tags' => ['Polyaspartic', 'Topcoat', 'Clear'],
            'price' => 285,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/blue_label_Poly.jpg?v=1746817730',
            'summary' => 'High-solids clear topcoat built for abrasion, chemical, and stain resistance with strong gloss retention.',
            'details' => ['Two-component clear topcoat', 'Excellent abrasion resistance', 'Good impact resistance', 'Low VOC options available'],
        ],
        [
            'slug' => 'crown-polymers-blue-label-epoxy-100-3-gallons-clear-copy',
            'title' => '8110 CrownSeal CRU UV Stable 1.5 Gallon Kit Urethane Top Coat',
            'category' => 'Protective Coatings',
            'tags' => ['Urethane', 'UV stable', 'Finish coat'],
            'price' => 204.48,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/Crown_Polymers_8110_A-600x495.jpg?v=1746818243',
            'summary' => 'Abrasion, chemical, and stain-resistant aliphatic polyester polyurethane finish coat for clear gloss or clear satin systems.',
            'details' => ['UV-stable urethane finish', 'Clear gloss and satin options', 'Chemical and stain resistant', 'Professional finish coat'],
        ],
        [
            'slug' => '8312-crowncove™-high-build-thixotropic-epoxy',
            'title' => '8312 CrownCove - High-Build Thixotropic Epoxy',
            'category' => 'Cove Base',
            'tags' => ['Cove', 'Epoxy', 'Vertical application'],
            'price' => 285,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/Crown_Polymers_8312_A-600x495.jpg?v=1746826378',
            'summary' => 'Clear two-component thixotropic epoxy formulated for vertical cove base applications where sag resistance matters.',
            'details' => ['100% solids thermosetting epoxy', 'Hand-trowel applied', 'Designed for 4 inch and 6 inch cove', 'Strong sag resistance'],
        ],
        [
            'slug' => 'premera-t2-mcm-1-gallon',
            'title' => 'Premera T2 MCM 1 Gallon',
            'category' => 'Protective Coatings',
            'tags' => ['Topcoat', 'Concrete protection', 'Single component'],
            'price' => 165,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/premeraT2.jpg?v=1746826743',
            'summary' => 'Single-component clear coating for concrete, terrazzo, tile, and existing coating protection.',
            'details' => ['Spray-down sol-gel coating', 'Quartz mineral barrier', 'No backroll workflow', 'Clear protective finish'],
        ],
        [
            'slug' => 'wooster-br045-18-big-ben-roller-frame',
            'title' => 'Wooster BR045 18" Big Ben Roller Frame',
            'category' => 'Accessories',
            'tags' => ['Tools', 'Roller frame'],
            'price' => 39.99,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/071497134356.jpg?v=1746827459',
            'summary' => 'Lightweight 18 inch roller frame for professional coating installation.',
            'details' => ['Fits 18 inch roller covers', 'Lightweight polypropylene construction', 'Sherlock GT compatible', 'No tools required'],
        ],
        [
            'slug' => '18-speedsqueegee®-flat-stiff',
            'title' => '18" SpeedSqueegee Seymour Midwest',
            'category' => 'Accessories',
            'tags' => ['Tools', 'Squeegee'],
            'price' => 39.99,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/speedsqueegeeproductbrochure_2020_1.jpg?v=1747242051',
            'summary' => 'Flat stiff SpeedSqueegee for coating placement and controlled application rates.',
            'details' => ['Flat stiff blade option', 'Used for coating placement', 'Compatible with professional floor systems', 'Multiple notch rates available'],
        ],
        [
            'slug' => '1-4-40-lbs-flakes-box',
            'title' => '1/4" 40 lbs Flakes Box',
            'category' => 'Flakes',
            'tags' => ['Epoxy', 'Flakes', 'Broadcast media'],
            'price' => 120,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/1.jpg?v=1747166303',
            'summary' => 'Decorative epoxy flakes for durable, slip-resistant, and visually consistent floor systems.',
            'details' => ['40 lb box', 'Adds texture and color', 'Improves slip resistance', 'Common for garages, showrooms, and warehouses'],
        ],
        [
            'slug' => 'crown-polymers-8320-crownshield-all-n-one-epoxy',
            'title' => '8320 CrownShield All-n-One Epoxy 3 Gallon Clear',
            'category' => 'Epoxy Floor Coatings',
            'tags' => ['Epoxy', 'Hybrid', 'Chemical resistance'],
            'price' => 289.50,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/Crown_Polymers_8320_A-1-600x495.jpg?v=1747241308',
            'summary' => 'Hybrid Bis F and Bis A two-component epoxy for challenging environments requiring abrasion and chemical resistance.',
            'details' => ['100% solids hybrid epoxy', 'Low viscosity and low odor', 'Abrasion and chemical resistant', 'Multi-functional system component'],
        ],
        [
            'slug' => 'vantage-roller-cover-18-in-3-8-nap',
            'title' => 'Vantage Roller Cover | 18 in 3/8 Nap',
            'category' => 'Accessories',
            'tags' => ['Tools', 'Roller cover'],
            'price' => 9.99,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/GM-939M.webp?v=1747242423',
            'summary' => 'Industrial roller cover for coating floors with a professional 3/8 inch nap.',
            'details' => ['18 inch roller cover', '3/8 inch nap', 'Industrial coating use', 'Available individually or by box'],
        ],
        [
            'slug' => 'epoxy-resin-solid-epoxy-pigments',
            'title' => 'Pigments IN STOCK White | Medium Gray | Black | Epoxy Pigments',
            'category' => 'Metallic Pigments',
            'tags' => ['Pigment', 'Epoxy color', 'In stock'],
            'price' => null,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/white_color_pigment.jpg?v=1747250508',
            'summary' => 'Standard epoxy colors and safety pigments for pigmented base coats in decorative coating systems.',
            'details' => ['White, medium gray, and black options', 'Used in base coats', 'Supports flake and metallic systems', 'In-stock color program'],
        ],
        [
            'slug' => '810-crowncrete-u-skim-coat',
            'title' => '810 CrownCrete U Skim Coat',
            'category' => 'Urethane Cement',
            'tags' => ['Urethane cement', 'Skim coat'],
            'price' => null,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/810partb.jpg?v=1747257536',
            'summary' => 'Three-part urethane polymer concrete high-build coating for thin film roll-applied concrete resurfacing.',
            'details' => ['Three-part urethane polymer concrete', 'Thin film roll-applied system', 'Concrete protection flooring product', 'Quote required for project pricing'],
        ],
        [
            'slug' => '814-crowncrete-u-1-4',
            'title' => '814 CrownCrete U 1/4',
            'category' => 'Urethane Cement',
            'tags' => ['Urethane cement', 'Self-leveling'],
            'price' => null,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/814.jpg?v=1747260771',
            'summary' => 'Self-leveling urethane-cement mortar designed to protect concrete from abrasion, chemicals, impact, and temperature cycling.',
            'details' => ['Three-component flowable overlayment', '1/4 inch system profile', 'Handles thermal cycling', 'Industrial concrete protection'],
        ],
        [
            'slug' => '818-crowncrete-u-1-8',
            'title' => '818 CrownCrete U 1/8',
            'category' => 'Urethane Cement',
            'tags' => ['Urethane cement', 'Self-leveling'],
            'price' => null,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/818B.jpg?v=1747261029',
            'summary' => 'Self-leveling urethane cement overlayment for industrial floors exposed to impact, abrasion, and chemicals.',
            'details' => ['Three-component flowable system', '1/8 inch system profile', 'Industrial floor resurfacing', 'Project quote required'],
        ],
        [
            'slug' => '838-crowncrete-u-3-8-trowel-grade',
            'title' => '838 CrownCrete U 3/8 Trowel Grade',
            'category' => 'Urethane Cement',
            'tags' => ['Urethane cement', 'Trowel grade'],
            'price' => null,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/838.jpg?v=1747261088',
            'summary' => 'Heavy-duty high-density trowel-grade urethane polymer concrete system for demanding floor environments.',
            'details' => ['Three-part trowel-grade product', '3/8 inch heavy-duty system', 'High-density packed mortar', 'Built for demanding industrial floors'],
        ],
        [
            'slug' => 'metallic-pigments',
            'title' => 'Metallic Pigments',
            'category' => 'Metallic Pigments',
            'tags' => ['Metallic', 'Pigment'],
            'price' => 30,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/8.png?v=1747427205',
            'summary' => 'Metallic pigment options for high-gloss decorative epoxy floors with depth and movement.',
            'details' => ['Decorative metallic finish', 'Used with clear epoxy systems', 'Creates depth and visual movement', 'Multiple color options'],
        ],
        [
            'slug' => 'metallic-epoxy-100-lv-3-gallon-clear',
            'title' => 'Metallic Epoxy 100 LV 3 gallon Clear',
            'category' => 'Epoxy Floor Coatings',
            'tags' => ['Metallic epoxy', 'Clear epoxy'],
            'price' => 150,
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/blue_label_epoxy.jpg?v=1746817187',
            'summary' => 'Clear low-viscosity epoxy for metallic floor systems and decorative high-gloss applications.',
            'details' => ['Clear LV epoxy', 'Made for metallic systems', 'High-gloss decorative finish', 'Pairs with metallic pigment packs'],
        ],
    ],
    'collections' => [
        'epoxy-for-concrete-floors' => [
            'title' => 'Epoxy For Concrete Floors',
            'summary' => 'High-performance epoxy floor coatings, pigments, flakes, and clear systems for residential, commercial, and industrial concrete.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/BlueLabel.jpg?v=1746812312',
            'products' => ['crown-polymers-blue-label-epoxy-100-3-gallons-clear', 'crown-polymers-8320-crownshield-all-n-one-epoxy', 'metallic-epoxy-100-lv-3-gallon-clear', 'epoxy-resin-solid-epoxy-pigments', '1-4-40-lbs-flakes-box'],
        ],
        'protective-coat' => [
            'title' => 'Protective Coatings',
            'summary' => 'Clear topcoats and protective finishes for abrasion resistance, stain resistance, UV stability, and long-term gloss retention.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/premeraT2.jpg?v=1746826743',
            'products' => ['crown-polymers-blue-label-polyaspartic-100-3-gallons-clear', 'crown-polymers-blue-label-epoxy-100-3-gallons-clear-copy', 'premera-t2-mcm-1-gallon'],
        ],
        'cove-base' => [
            'title' => 'Cove Base',
            'summary' => 'High-build cove base epoxy for vertical transitions, sanitary details, and industrial floor-wall interfaces.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/Crown_Polymers_8312_A-600x495.jpg?v=1746826378',
            'products' => ['8312-crowncove™-high-build-thixotropic-epoxy'],
        ],
        'accessories' => [
            'title' => 'Accessories',
            'summary' => 'Professional rollers, squeegees, and installation tools for coating crews.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/speedsqueegeeproductbrochure_2020_1.jpg?v=1747242051',
            'products' => ['wooster-br045-18-big-ben-roller-frame', '18-speedsqueegee®-flat-stiff', 'vantage-roller-cover-18-in-3-8-nap'],
        ],
        'flakes' => [
            'title' => 'Flakes',
            'summary' => 'Decorative broadcast flakes for texture, durability, and slip-resistant epoxy flooring systems.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/1.jpg?v=1747166303',
            'products' => ['1-4-40-lbs-flakes-box'],
        ],
        'urethane-cement' => [
            'title' => 'Urethane Cement',
            'summary' => 'CrownCrete U urethane cement systems for industrial kitchens, breweries, manufacturing, and heavy service concrete.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/814.jpg?v=1747260771',
            'products' => ['810-crowncrete-u-skim-coat', '814-crowncrete-u-1-4', '818-crowncrete-u-1-8', '838-crowncrete-u-3-8-trowel-grade'],
        ],
        'metallic-colors' => [
            'title' => 'Metallic Colors',
            'summary' => 'Metallic pigment systems and clear epoxy for decorative floors with a polished, high-gloss finish.',
            'image' => 'https://cdn.shopify.com/s/files/1/0829/0277/8176/files/8.png?v=1747427205',
            'products' => ['metallic-pigments', 'metallic-epoxy-100-lv-3-gallon-clear'],
        ],
    ],
    'waterproofing_applications' => [
        'roof-plaza-deck-waterproofing' => [
            'slug' => 'roof-plaza-deck-waterproofing',
            'title' => 'Roof and Plaza Deck Waterproofing',
            'summary' => 'Flexible Polycoat waterproofing systems for roof decks, plaza decks, pedestrian areas, vehicular areas, and green roof assemblies.',
            'image' => 'https://www.polycoatusa.com/wp-content/uploads/2026/02/Polycoat-Roof-Plaza-Desk-1.png',
            'hero_image' => 'https://www.polycoatusa.com/wp-content/uploads/2026/02/Waterproofing-Header-Hero-LAX.jpg',
            'items' => ['Pedestrian decking systems', 'Vehicular decking systems', 'Green roof waterproofing'],
            'quote_focus' => 'Share deck substrate, slope, drainage, traffic type, square footage, finish requirement, and construction schedule.',
            'products' => [
                ['title' => 'Polydeck® 100', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/POLYDECK20100-concrete-.jpg', 'summary' => 'Light-service pedestrian traffic deck system for liquid-applied waterproofing assemblies.', 'tags' => ['Pedestrian', 'Light service']],
                ['title' => 'Polydeck® 100SC', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/POLYDECK20100SC-concrete20updated.jpg', 'summary' => 'Pedestrian deck waterproofing option for light service projects needing a low-odor system path.', 'tags' => ['Pedestrian', 'Low odor']],
                ['title' => 'Polydeck® 150/150SC', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/POLYDECK20150_150SC-Concrete20updated.jpg', 'summary' => 'Everyday-use pedestrian traffic deck system with primer, basecoat, aggregate coat, and topcoat layers.', 'tags' => ['Pedestrian', 'Everyday use']],
                ['title' => 'Polydeck® 160/160SC', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/POLYDECK2016020Updated.jpg', 'summary' => 'High-performance pedestrian waterproofing system for concrete, plywood, and metal surfaces.', 'tags' => ['High performance', 'Decking']],
                ['title' => 'Polydeck® 160MR/160MR-SC', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/POLYDECK20160MR-Rubber-wood20Updated.jpg', 'summary' => 'Metal-reinforced pedestrian deck system for assemblies needing additional reinforcement.', 'tags' => ['Reinforced', 'Pedestrian']],
                ['title' => 'Polydeck® 180/180SC', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/Polydeck20180_180SC.jpg', 'summary' => 'Moisture-cured waterproofing deck system for daily service conditions.', 'tags' => ['Moisture cured', 'Decking']],
                ['title' => 'Polydeck® 355', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/POLYDECK20355-wood_updated.jpg', 'summary' => 'Pedestrian traffic deck system for plywood assemblies requiring fire-rated waterproofing direction.', 'tags' => ['Plywood', 'Fire rated']],
                ['title' => 'Polydeck® 400', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/POLYDECK20400_updated.jpg', 'summary' => 'Liquid-applied pedestrian waterproofing system for plywood assemblies with Class A fire-rating needs.', 'tags' => ['Class A', 'Plywood']],
                ['title' => 'Polydeck® 555', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/POLYDECK20555-wood_update.jpg', 'summary' => 'Rapid return-to-service pedestrian waterproofing system using high-solids polyurethane/polyurea technology.', 'tags' => ['Fast cure', 'High solids']],
                ['title' => 'Polydeck® MR', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/Polydeck20MR.jpg', 'summary' => 'Mechanical room waterproofing system for tough, durable service areas.', 'tags' => ['Mechanical room', 'Durable']],
            ],
        ],
        'parking-traffic-coatings' => [
            'slug' => 'parking-traffic-coatings',
            'title' => 'Parking and Traffic Coatings',
            'summary' => 'Polycoat traffic coating systems for parking decks, plaza traffic surfaces, ramps, and drive lanes.',
            'image' => 'https://www.polycoatusa.com/wp-content/uploads/2026/02/Polycoat-Parketing-Traffic-Coatings-1.png',
            'hero_image' => 'https://www.polycoatusa.com/wp-content/uploads/2026/02/Waterproofing-Header-Hero-LAX.jpg',
            'items' => ['Parking deck coatings', 'Plaza deck vehicular systems', 'Ramp and drive lane waterproofing'],
            'quote_focus' => 'Share whether the area is pedestrian, vehicular, ramp, drive lane, exposed deck, or occupied structure work.',
            'products' => [
                ['title' => 'Poly-I-Gard® 125', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/Poly-I-Gard-125-Light-Traffic-Graphic-2-Updated.jpg', 'summary' => 'Everyday-use vehicular traffic deck system for liquid-applied polyurethane waterproofing assemblies.', 'tags' => ['Vehicular', 'Everyday use']],
                ['title' => 'Poly-I-Gard® E', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2026/04/Poly-i-gard-E-Thumbnail.png', 'summary' => 'Fast-curing polyurethane and epoxy traffic deck system for durable waterproof protection.', 'tags' => ['Fast cure', 'Traffic']],
                ['title' => 'Poly-I-Gard® FC UE', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2026/04/Poly-I-Gard-FC-UE-thumbnail.png', 'summary' => 'Fast-curing 100% solids polyurethane/polyurea system for low-odor vehicular traffic coating projects.', 'tags' => ['100% solids', 'Low odor']],
                ['title' => 'Poly-I-Gard™ 246', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/POLY-I-GARD-246_updated.jpg', 'summary' => 'High-solids vehicular traffic deck system built around epoxy primer and high-tensile polyurethane.', 'tags' => ['High solids', 'Vehicular']],
                ['title' => 'Poly-I-Gard™ 246 SC', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2026/04/Poly-I-Gard-246SC-Thumbnail.png', 'summary' => 'Vehicular traffic deck system option for projects needing a 246-series system path.', 'tags' => ['Traffic deck', 'Vehicular']],
                ['title' => 'Poly-I-Gard™ 295/295 OF', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/PolyIgard295.jpg', 'summary' => 'Odor-friendly, rapid-setting traffic deck system for waterproof vehicular surfaces.', 'tags' => ['Odor friendly', 'Rapid setting']],
                ['title' => 'Poly-I-Gard™ 435/435SC', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/PolyIgard435.jpg', 'summary' => 'Durable vehicular traffic deck system for surfaces exposed to regular vehicle movement.', 'tags' => ['Durable', 'Vehicular']],
                ['title' => 'Poly-I-Gard™ 575FC', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/PolyIgard575.jpg', 'summary' => 'Fast-cure polyurethane/polyurea traffic coating system for rapid return-to-service needs.', 'tags' => ['Fast cure', 'Polyurea']],
                ['title' => 'Poly-I-Gard™ 575FR', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/POLY-I-GARD20575FR-Updated.jpg', 'summary' => 'Fire-rated vehicular traffic deck system for demanding waterproofing and traffic exposure.', 'tags' => ['Fire rated', 'Traffic']],
            ],
        ],
        'below-grade-foundation-protection' => [
            'slug' => 'below-grade-foundation-protection',
            'title' => 'Below-Grade and Foundation Protection',
            'summary' => 'Polycoat waterproofing direction for foundations, retaining walls, elevator pits, and below-grade assemblies.',
            'image' => 'https://www.polycoatusa.com/wp-content/uploads/2026/02/Polycoat-Below-Grade-Foundation-1.png',
            'hero_image' => 'https://www.polycoatusa.com/wp-content/uploads/2026/02/Waterproofing-Header-Hero-LAX.jpg',
            'items' => ['Foundation waterproofing', 'Retaining wall coatings', 'Elevator pit protection'],
            'quote_focus' => 'Share whether the condition is positive-side, blind-side, vertical wall, horizontal deck, elevator pit, or repair work.',
            'products' => [
                ['title' => 'Polycoat-Aquaseal™ 5000', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/Polycoat_Aquaseal_5000_SC_H.jpg', 'summary' => 'Single-component liquid-applied polyurethane waterproofing membrane for below-grade protection conversations.', 'tags' => ['Below grade', 'Membrane']],
                ['title' => 'Polycoat-Aquaseal™ 5000 WC/GC', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/Polycoat_Aquaseal_5000_WC_H.jpg', 'summary' => 'Water-curable waterproofing membrane system for vertical and horizontal surface protection.', 'tags' => ['Water curable', 'Vertical/horizontal']],
                ['title' => 'Polycoat-Aquatight™', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/logo.jpg.jpg', 'summary' => 'Solvent-free, high-solids aromatic polyurethane waterproofing membrane system.', 'tags' => ['Solvent free', 'High solids']],
                ['title' => 'Polycoat® PC-IM 129 System', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/Polycoat_PC_IM_129_V_B_Black_4G.jpg', 'summary' => 'Two-component asphalt-extended aromatic polyurethane waterproofing membrane system.', 'tags' => ['Two component', 'Membrane']],
                ['title' => 'Poly-I-Gard™ 575FR Under Tile', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/logo.jpg.jpg', 'summary' => 'Under-tile waterproofing system direction for assemblies needing tile-ready protection.', 'tags' => ['Under tile', 'Waterproofing']],
            ],
        ],
        'water-containment-treatment-facilities' => [
            'slug' => 'water-containment-treatment-facilities',
            'title' => 'Water Containment and Treatment Facilities',
            'summary' => 'Polycoat coating and waterproofing support for potable water tanks, wastewater treatment, marine exposure, and pier protection.',
            'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/Water_containment.jpg',
            'hero_image' => 'https://www.polycoatusa.com/wp-content/uploads/2026/02/Waterproofing-Header-Hero-LAX.jpg',
            'items' => ['Potable water tank linings', 'Wastewater treatment coatings', 'Marine and pier protection'],
            'quote_focus' => 'Share whether the project involves concrete or metal, immersion, wastewater, potable water, marine exposure, or chemical service.',
            'products' => [
                ['title' => 'Polycoat-Aquaseal™ 5000', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/Polycoat_Aquaseal_5000_SC_H.jpg', 'summary' => 'Liquid-applied polyurethane waterproofing membrane for water-exposure coating conversations.', 'tags' => ['Waterproofing', 'Membrane']],
                ['title' => 'Polycoat-Aquaseal™ 5000 WC/GC', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/Polycoat_Aquaseal_5000_WC_H.jpg', 'summary' => 'Water-curable membrane system for vertical and horizontal waterproofing scopes.', 'tags' => ['Water curable', 'Coating']],
                ['title' => 'Polycoat-Aquatight™', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/logo.jpg.jpg', 'summary' => 'High-solids aromatic polyurethane waterproofing membrane for containment-related review.', 'tags' => ['High solids', 'Polyurethane']],
                ['title' => 'Polycoat® PC-IM 129 System', 'image' => 'https://www.polycoatusa.com/wp-content/uploads/2025/08/Polycoat_PC_IM_129_V_B_Black_4G.jpg', 'summary' => 'Two-component polyurethane waterproofing membrane system for project-specific specification review.', 'tags' => ['Two component', 'System']],
            ],
        ],
    ],
    'pages' => [
        'contact' => [
            'title' => 'Contact',
            'summary' => 'Talk to a Bay Area epoxy and waterproofing supply specialist.',
            'sections' => [
                ['title' => 'Hayward Warehouse', 'body' => 'Visit or contact the team at 2495 American Ave, Hayward, CA 94545 for product availability, job quoting, and contractor supply support.'],
                ['title' => 'Fastest Response', 'body' => 'Call, text, or WhatsApp the team for product recommendations, order planning, and pickup coordination.'],
            ],
        ],
        'about-us' => [
            'title' => 'About Us',
            'summary' => 'Industrial epoxy, waterproofing, and concrete coating supplies for contractors across the Bay Area and California.',
            'sections' => [
                ['title' => 'Wholesale Focus', 'body' => 'Bay Area Epoxy Wholesale helps contractors source professional coating materials with practical product guidance, local pickup coordination, and project-focused support.'],
                ['title' => 'Product Systems', 'body' => 'We organize materials by flooring system so crews can quickly compare epoxy, urethane cement, flakes, pigments, topcoats, and waterproofing options.'],
            ],
        ],
        'epoxy-calculator' => [
            'title' => 'Epoxy Calculator',
            'summary' => 'Estimate material needs for epoxy coating systems before requesting a final quote.',
            'sections' => [
                ['title' => 'Coverage Planning', 'body' => 'Share square footage, concrete condition, target system, and desired build thickness so we can confirm gallons, flakes, tools, and topcoat needs.'],
                ['title' => 'Quote Support', 'body' => 'Calculator outputs should be treated as planning estimates. Final coverage depends on porosity, repair work, broadcast rate, and system design.'],
            ],
        ],
        'color-chart' => [
            'title' => 'Color Chart',
            'summary' => 'Review standard pigment, flake, quartz, and metallic options for epoxy floor systems.',
            'sections' => [
                ['title' => 'Common Colors', 'body' => 'White, medium gray, black, metallic pigments, and decorative flake blends are organized for fast contractor selection.'],
                ['title' => 'Sample Matching', 'body' => 'For project-critical colors, confirm samples and batch availability with the warehouse before installation.'],
            ],
        ],
        'brochures-resources' => [
            'title' => 'Brochures Resources',
            'summary' => 'Technical resources, product literature, and specification support for coating crews.',
            'sections' => [
                ['title' => 'Product Literature', 'body' => 'Request data sheets, brochures, installation notes, and brand documentation for the epoxy, urethane cement, waterproofing, and protective coating systems on your project.'],
                ['title' => 'Specification Help', 'body' => 'Send project conditions through WhatsApp and the team can help identify the right primer, body coat, broadcast, and finish coat.'],
            ],
        ],
        'structural-concrete-repair' => [
            'title' => 'Structural Concrete Repair',
            'summary' => 'Authorized Chemco Systems distributor support for CCS epoxy and polyurea products used in structural concrete crack repair, bonding, grouting, coatings, and protection.',
            'sections' => [
                ['title' => 'Authorized Chemco Systems Distributor', 'body' => 'Bay Area Epoxy Wholesale supports contractors, property managers, and engineers with Chemco CCS product selection, quote coordination, and local project support.'],
                ['title' => 'Specification Support', 'body' => 'Share repair conditions, drawings, crack details, exposure, temperature, traffic, and structural requirements so the team can help organize the Chemco material request.'],
            ],
        ],
        'deck-waterproofing-in-california' => [
            'title' => 'Deck Waterproofing in California',
            'summary' => 'Polycoat deck waterproofing systems for general contractors, waterproofing specialists, decks, parking structures, foundations, and containment projects in California.',
            'sections' => [
                ['title' => 'Authorized Polycoat Distributor', 'body' => 'Bay Area Epoxy Wholesale supports California contractors with Polycoat waterproofing materials, project quoting, and local pickup coordination.'],
                ['title' => 'Project Support', 'body' => 'Share drawings, substrate conditions, traffic exposure, square footage, and project schedule so the team can help narrow product direction and quote needs.'],
            ],
        ],
        'training-quick-tips' => [
            'title' => 'Training Quick Tips',
            'summary' => 'Practical tips for epoxy, urethane cement, waterproofing, and decorative concrete coating installation.',
            'sections' => [
                ['title' => 'Crew-Oriented Guidance', 'body' => 'Get practical guidance on surface prep, mixing, coverage, working time, broadcast technique, and topcoat selection before the crew mobilizes.'],
                ['title' => 'Local Support', 'body' => 'Contractors can contact the Hayward team for job-specific recommendations before mobilizing crews.'],
            ],
        ],
        'training-schedule' => [
            'title' => 'Training Schedule',
            'summary' => 'Upcoming product training and contractor education events.',
            'sections' => [
                ['title' => 'Request Schedule', 'body' => 'Use WhatsApp to ask about upcoming hands-on trainings, product demos, and manufacturer sessions.'],
                ['title' => 'Topics', 'body' => 'Epoxy flakes, metallic epoxy, urethane cement, waterproof deck systems, prep standards, and topcoat workflows.'],
            ],
        ],
        'urethane-cement' => [
            'title' => 'Urethane Cement',
            'summary' => 'Heavy-duty urethane cement systems for industrial concrete floors exposed to thermal shock, chemicals, and impact.',
            'sections' => [
                ['title' => 'Industrial Protection', 'body' => 'CrownCrete U systems cover skim coat, self-leveling, and trowel-grade profiles for kitchens, manufacturing, breweries, and processing spaces.'],
                ['title' => 'Project Selection', 'body' => 'System choice depends on traffic, temperature, cleaning chemicals, substrate condition, and target thickness.'],
            ],
        ],
        'esd-static-dissipative-conductive' => [
            'title' => 'ESD Flooring Systems California',
            'summary' => 'Conductive and static dissipative flooring solutions for mission-critical California facilities.',
            'sections' => [
                ['title' => 'Controlled Flooring', 'body' => 'Conductive and static dissipative systems for data centers, electronics manufacturing, laboratories, production, and controlled spaces.'],
                ['title' => 'Technical Confirmation', 'body' => 'ESD systems should be quoted with performance requirements, substrate details, grounding design, and maintenance expectations.'],
            ],
        ],
        'epoxy-supplier-california' => [
            'title' => 'Epoxy Supplier California',
            'summary' => 'Wholesale epoxy flooring supplies and waterproofing products serving Hayward, the Bay Area, and California contractors.',
            'sections' => [
                ['title' => 'California Supply', 'body' => 'Contractors can source epoxy, polyaspartic, urethane cement, flakes, pigments, and tools through the Hayward warehouse.'],
                ['title' => 'Professional Support', 'body' => 'The new site is designed around fast product selection, direct enquiry, and technical support instead of a Shopify cart.'],
            ],
        ],
    ],
    'esd_systems' => [
        'esd-conductive-mortar-system' => [
            'slug' => 'esd-conductive-mortar-system',
            'title' => 'ESD Conductive Mortar System',
            'type' => 'Conductive mortar',
            'image' => 'assets/esd-conductive-mortar.jpg',
            'profile' => 'Approx. 1/4 inch profile',
            'resistance' => '25,000 to 1,000,000 ohms',
            'summary' => 'Heavy-duty conductive urethane cement mortar for facilities that need static control plus impact, chemical, and thermal-shock durability.',
            'overview' => 'This conductive mortar path is built for demanding environments where static control has to work alongside heavy traffic, wet service, impact, cleaning exposure, and thermal cycling. Bay Area Epoxy Wholesale can help contractors confirm the material path, grounding requirements, and quote details before ordering.',
            'layers' => ['CrownCrete U Conductive Mortar', 'Conductive epoxy coating', 'ESD wax finish'],
            'ideal' => ['Battery facilities', 'Industrial manufacturing', 'Heavy traffic operations'],
            'quote_notes' => 'Share the floor condition, square footage, desired profile, traffic type, grounding plan, and whether the project needs conductive performance in the 25K to 1M ohm range.',
        ],
        'esd-conductive-system' => [
            'slug' => 'esd-conductive-system',
            'title' => 'ESD Conductive System',
            'type' => 'Conductive epoxy',
            'image' => 'assets/esd-conductive-system.jpg',
            'profile' => 'Approx. 50 mils',
            'resistance' => '25,000 to 1,000,000 ohms',
            'summary' => 'Conductive epoxy floor system for enhanced static control in high-density technology and precision production environments.',
            'overview' => 'This conductive epoxy system supports controlled spaces that need a thinner resin floor build with conductive performance. It is commonly reviewed for data, electronics, semiconductor, and precision manufacturing environments where ESD requirements need to be confirmed before installation.',
            'layers' => ['ESD conductive epoxy primer', 'ESD conductive epoxy coating', 'ESD wax finish'],
            'ideal' => ['High-density data centers', 'Semiconductor facilities', 'Electronics production'],
            'quote_notes' => 'Send project drawings, square footage, substrate condition, target resistance range, grounding details, and whether the system is for new construction or retrofit work.',
        ],
        'esd-mortar-system' => [
            'slug' => 'esd-mortar-system',
            'title' => 'ESD Mortar System',
            'type' => 'Static dissipative mortar',
            'image' => 'assets/esd-mortar-system.jpg',
            'profile' => 'Approx. 1/4 inch profile',
            'resistance' => '1,000,000 to 1,000,000,000 ohms',
            'summary' => 'Static dissipative mortar system for facilities needing a thicker, more durable floor build with controlled static performance.',
            'overview' => 'This mortar system is a heavier static dissipative build for facilities that need durability, controlled resistance, and a thicker floor profile. It fits production, processing, and lab environments where wheeled traffic and maintenance expectations need to be considered.',
            'layers' => ['CrownCrete U mortar', '8320 epoxy base coat', 'ESD static dissipative topcoat'],
            'ideal' => ['Industrial production', 'Processing plants', 'Labs with wheeled traffic'],
            'quote_notes' => 'Include the target static dissipative range, floor loading, cleaning exposure, thickness requirements, and schedule so the team can help organize the material request.',
        ],
        'esd-static-dissipative-system' => [
            'slug' => 'esd-static-dissipative-system',
            'title' => 'ESD Static Dissipative System',
            'type' => 'Static dissipative epoxy',
            'image' => 'assets/esd-static-dissipative-system.jpg',
            'profile' => 'Approx. 45 mils',
            'resistance' => '1,000,000 to 1,000,000,000 ohms',
            'summary' => 'Seamless static dissipative epoxy system for controlled environments that need easier maintenance and reliable long-term performance.',
            'overview' => 'This static dissipative epoxy path is a practical fit for controlled environments where teams need reliable ESD performance, a seamless floor, and easier maintenance than thicker mortar systems. It is often considered for data centers, telecom rooms, electronics labs, and similar spaces.',
            'layers' => ['ESD epoxy primer', 'ESD epoxy slurry', 'ESD static dissipative topcoat'],
            'ideal' => ['Data centers', 'Telecom facilities', 'Electronics labs'],
            'quote_notes' => 'Share the use environment, square footage, existing substrate, target resistance range, grounding approach, and maintenance expectations for the floor.',
        ],
    ],
    'chemco_structural_repair_categories' => [
        'ccs-bonders' => [
            'slug' => 'ccs-bonders',
            'title' => 'CCS Bonders',
            'image' => 'https://www.chemcosystems.com/images/kemko-bonders.png',
            'summary' => 'Filled liquid and paste adhesives for manual application.',
            'fit' => 'Bonding hardened concrete, setting anchors, repair details, and field-applied adhesive work.',
            'overview' => 'CCS bonders are used when concrete repair work needs filled liquid or paste adhesive options that can be placed manually by the crew. They fit repair details where surface preparation, bond line control, and working time matter.',
            'applications' => ['Concrete bonding repairs', 'Anchor and dowel setting conversations', 'Paste adhesive repair details', 'Manual field application', 'Structural repair preparation'],
            'products' => [
                ['name' => 'CCS Bonder 217 Security Seal', 'summary' => 'Epoxy paste for filling, fairing, leveling, and bonding security sealant.'],
                ['name' => 'CCS Bonder Liquid LWL', 'summary' => 'Long pot life structural epoxy adhesive bonding agent.'],
                ['name' => 'CCS Bonder Liquid SWL', 'summary' => 'Short pot life structural epoxy adhesive liquid bonding agent.'],
                ['name' => 'CCS Bonder Paste LoTemp', 'summary' => 'Low temperature, short work life epoxy paste adhesive for bonding.'],
                ['name' => 'CCS Bonder Paste LWL', 'summary' => 'Long working life epoxy paste adhesive for bonding.'],
                ['name' => 'CCS Bonder Paste SWL', 'summary' => 'Short working life epoxy paste adhesive for bonding.'],
                ['name' => 'CCS Bonder Paste, Chem/Rad Resistant', 'summary' => 'Epoxy paste adhesive for chemical and radiation resistant bonding.'],
                ['name' => 'CCS Bonder Paste, Low Modulus', 'summary' => 'Toughened epoxy paste adhesive for spall repair and bonding.'],
                ['name' => 'CCS Bonder Paste, Traffic Marker', 'summary' => 'Epoxy paste adhesive for bonding traffic markers to pavement.'],
            ],
            'quote_notes' => 'Share substrate condition, repair profile, temperature, vertical or horizontal placement, required working time, and whether the adhesive will be used for bonding, anchoring, or patching support.',
        ],
        'ccs-injection' => [
            'slug' => 'ccs-injection',
            'title' => 'CCS Injection',
            'image' => 'https://www.chemcosystems.com/images/ccs-injection.png',
            'summary' => 'Crack injection resins for automatic pumps and surface seal work.',
            'fit' => 'Structural cracks, load-bearing repairs, walls, slabs, columns, and repair programs that need pumpable resin systems.',
            'overview' => 'CCS injection products support crack repair projects where resin viscosity, crack width, pump equipment, gel time, moisture exposure, and load-bearing performance need to be coordinated before work starts.',
            'applications' => ['Structural crack injection', 'Automatic pump resin placement', 'Surface seal coordination', 'Load-bearing crack repairs', 'Wall, slab, and column repairs'],
            'products' => [
                ['name' => 'CCS Grout, Ducputty', 'summary' => 'Epoxy for underwater and splash zone application.'],
                ['name' => 'CCS Stripseal', 'summary' => 'Non-sag polyurea crack sealer for concrete and masonry substrates.'],
                ['name' => 'CCS SuperSEAL', 'summary' => 'Extremely short working time paste for sealing cracks prior to injection.'],
                ['name' => 'CCS IR Grout, Capsule and Pressure Pot', 'summary' => 'Epoxy adhesive for pressure injection grouting.'],
                ['name' => 'CCS IR Grout, High Temperature', 'summary' => 'Structural epoxy adhesive for pressure injection grouting.'],
                ['name' => 'CCS Low Exotherm IR', 'summary' => 'Large void and wide crack structural epoxy adhesive pressure injection resin.'],
                ['name' => 'CCS IR Grout, Low Modulus', 'summary' => 'Low modulus epoxy adhesive for pressure injection grouting.'],
                ['name' => 'CCS Low Viscosity IR', 'summary' => 'Ultra low viscosity structural epoxy adhesive injection resin.'],
                ['name' => 'CCS IR Grout, Seal', 'summary' => 'Fast cure epoxy paste adhesive for crack sealing or bonding.'],
                ['name' => 'CCS Slump Pumping IR', 'summary' => 'Slump pumping structural epoxy adhesive for pressure injection.'],
                ['name' => 'CCS Standard IR', 'summary' => 'Structural epoxy adhesive injection resin for pressure injection.'],
                ['name' => 'CCS HiAmb IR', 'summary' => 'High ambient temperature epoxy adhesive for pressure injection grouting.'],
                ['name' => 'CCS IR Grout, Underwater', 'summary' => 'Structural epoxy adhesive for pressure injection grouting.'],
            ],
            'quote_notes' => 'Share crack width and depth, linear footage, access, active or dormant movement, moisture condition, injection equipment, and any ASTM C881 or AASHTO M235 requirement.',
        ],
        'ccs-grouts' => [
            'slug' => 'ccs-grouts',
            'title' => 'CCS Grouts',
            'image' => 'https://www.chemcosystems.com/images/ccs-grouts.png',
            'summary' => 'Patching and control joint epoxies and polyureas, including FAA P606 grout.',
            'fit' => 'Spall repair, control joints, slab patching, polymer concrete grout, and traffic-exposed repairs.',
            'overview' => 'CCS grouts are used for patching, control joint, and polymer concrete grout conversations where traffic exposure, aggregate loading, return-to-service, and repair depth shape product selection.',
            'applications' => ['Concrete patching', 'Control joint repair', 'FAA P606 grout conversations', 'Spall repair', 'Traffic-exposed slab repairs'],
            'products' => [
                ['name' => 'CCS Grout, Control Joint', 'summary' => 'Flexible epoxy sealant for control joints, sawcuts, and detector loops.'],
                ['name' => 'CCS Grout, Control Joint HB', 'summary' => 'Control joint filler and embedded wire/can light sealer.'],
                ['name' => 'CCS Grout, Dowel/Rebar/Bolt, LWL', 'summary' => 'Epoxy paste adhesive for dowel, rebar, and bolt grouting.'],
                ['name' => 'CCS Grout, Dowel/Rebar/Bolt, SWL', 'summary' => 'Epoxy paste adhesive for dowel, rebar, and bolt grouting.'],
                ['name' => 'CCS Grout, Polyurea LWL', 'summary' => 'Elastomeric polyurea binder for joints, nosing, and spall repair.'],
                ['name' => 'CCS Grout, Polyurea SWL', 'summary' => 'Elastomeric polyurea binder for joint filling, nosing, and spall repair.'],
            ],
            'quote_notes' => 'Share repair dimensions, depth, traffic exposure, aggregate plan, joint movement, return-to-service timing, and whether the project is commercial, industrial, airport, or infrastructure work.',
        ],
        'ccs-coatings' => [
            'slug' => 'ccs-coatings',
            'title' => 'CCS Coatings',
            'image' => 'https://www.chemcosystems.com/images/ccs-coatings.png',
            'summary' => 'Industrial-use high-solids, 0 VOC coatings for concrete protection and high acid resistance.',
            'fit' => 'Chemical exposure, protective concrete coatings, primer work, facility maintenance, and containment-adjacent protection.',
            'overview' => 'CCS coatings support concrete protection projects where high-solids chemistry, VOC requirements, acid resistance, primer needs, and facility exposure drive the coating system conversation.',
            'applications' => ['Concrete protection coatings', 'Chemical exposure areas', 'Industrial maintenance work', 'Primer coating conversations', 'High acid resistance needs'],
            'products' => [
                ['name' => 'CCS Coating, AC-1 for Asphalt', 'summary' => 'Chemical resistant epoxy coating for asphalt pavement.'],
                ['name' => 'CCS Coating, Concentrated Sulfuric Acid Resistance Coating and Surfacing (CSA)', 'summary' => 'Concentrated sulfuric acid resistance coating and surfacing.'],
                ['name' => 'CCS Coating, Epoxy Healer Sealer', 'summary' => 'Ultra low viscosity epoxy penetrant for topical applications.'],
                ['name' => 'CCS Coating, FC', 'summary' => 'Epoxy coating for direct food contact in dry bulk and aqueous service.'],
                ['name' => 'CCS Coating, General Purpose', 'summary' => 'Epoxy coating for common industrial chemicals.'],
                ['name' => 'CCS Coating, High Build Marine Structures', 'summary' => 'Epoxy coating for concrete and steel marine applications.'],
                ['name' => 'CCS Coating, High Chemical Resistance', 'summary' => 'Epoxy coating for strong industrial chemicals.'],
                ['name' => 'CCS Coating, High Temp', 'summary' => 'High HDT epoxy coating for strong industrial chemicals.'],
                ['name' => 'CCS Coating, Marine Structures', 'summary' => 'Epoxy coating for concrete and steel marine applications.'],
                ['name' => 'CCS Coating, MVR Primer', 'summary' => 'For slab-on-grade concrete with high moisture vapor transmission.'],
                ['name' => 'CCS Coating, Polyurea Membrane', 'summary' => 'Elastomeric polyurea membrane for waterproof surfacings.'],
                ['name' => 'CCS QuikPrime', 'summary' => 'Structural epoxy adhesive primer for polymer coating and flooring systems.'],
                ['name' => 'CCS Coating, Utility', 'summary' => 'Flexible epoxy coating for economical surfacings.'],
                ['name' => 'CCS Coating, Utility LV', 'summary' => 'Flexible epoxy coating for economical surfacings.'],
            ],
            'quote_notes' => 'Share chemical exposure, cleaning procedures, substrate age, moisture condition, traffic type, required finish, VOC requirement, and target installation window.',
        ],
        'ccs-binders' => [
            'slug' => 'ccs-binders',
            'title' => 'CCS Binders',
            'image' => 'https://www.chemcosystems.com/images/ccs-binders.png',
            'summary' => 'Unfilled low-viscosity resins for patching and overlays used with high aggregate loading.',
            'fit' => 'Polymer concrete, overlays, large void repairs, custom aggregate blends, and contractor-controlled aggregate sourcing.',
            'overview' => 'CCS binders are used when low-viscosity resin needs to be paired with high aggregate loading for patching, overlays, polymer concrete grout, or large-void repair approaches.',
            'applications' => ['Polymer concrete grout', 'High aggregate loading', 'Large void repairs', 'Patching and overlays', 'Custom aggregate blend conversations'],
            'products' => [
                ['name' => 'CCS Binder, Bridge Deck', 'summary' => 'Low modulus epoxy binder for protective overlays.'],
                ['name' => 'CCS Binder, Flooring-Decorative', 'summary' => 'Epoxy binder for decorative aggregate surfacing.'],
                ['name' => 'CCS Binder, Flooring-Industrial', 'summary' => 'Epoxy binder for industrial and institutional floor surfacings.'],
                ['name' => 'CCS Binder, Patch - Nosing - Slurry', 'summary' => 'Low modulus toughened binder for epoxy mortars and concretes.'],
                ['name' => 'CCS Binder, Polyurea LWL', 'summary' => 'Elastomeric polyurea binder for joints, nosing, and spall repair.'],
            ],
            'quote_notes' => 'Share void size, depth, aggregate source, mix design needs, placement temperature, expected load, exposure, and whether a gap-graded aggregate blend is being considered.',
        ],
    ],
    'posts' => [
        [
            'blog' => 'news',
            'slug' => 'epoxy-concrete-coatings-the-ideal-solution-for-food-beverage-manufacturing',
            'title' => 'Epoxy Concrete Coatings: The Ideal Solution for Food & Beverage Manufacturing',
            'date' => '2025-01-14',
            'summary' => 'How epoxy coating systems support cleanability, durability, and chemical resistance in food and beverage facilities.',
        ],
        [
            'blog' => 'news',
            'slug' => 'epoxy-flooring-solutions-for-wineries-strength-durability-and-aesthetic-excellence',
            'title' => 'Epoxy Flooring Solutions for Wineries: Strength, Durability, and Aesthetic Excellence',
            'date' => '2025-01-22',
            'summary' => 'Flooring considerations for wineries balancing durability, cleanability, and a polished guest-facing finish.',
        ],
        [
            'blog' => 'news',
            'slug' => 'why-removing-gypsum-flooring-is-essential-for-durable-and-long-lasting-results-for-metallic-floor-epoxy-floors-and-urethane-cement-floors',
            'title' => 'Why Removing Gypsum Flooring Is Essential for Durable and Long-Lasting Results',
            'date' => '2025-02-05',
            'summary' => 'Why substrate removal and preparation matter before metallic epoxy and urethane cement installations.',
        ],
        [
            'blog' => 'news',
            'slug' => 'exploring-crowncrete-u-versatile-solutions-for-industrial-flooring-needs',
            'title' => 'Exploring CrownCrete U: Versatile Solutions for Industrial Flooring Needs',
            'date' => '2025-02-18',
            'summary' => 'A contractor-focused look at urethane cement profiles for demanding industrial flooring conditions.',
        ],
        [
            'blog' => 'news',
            'slug' => 'quartz-double-broadcast-system-enhance-durability-and-safety-with-the-crownquartz-db-color-quartz-system',
            'title' => 'Quartz Double Broadcast System: Enhance Durability and Safety',
            'date' => '2025-02-26',
            'summary' => 'How double broadcast quartz systems add texture, durability, and traction to resinous floors.',
        ],
        [
            'blog' => 'news',
            'slug' => 'grind-seal-concrete-with-crownseal-8112-a-reliable-solution-for-durable-and-safe-concrete-coatings',
            'title' => 'Grind & Seal Concrete with CrownSeal 8112',
            'date' => '2025-03-04',
            'summary' => 'A practical overview of grind-and-seal concrete coating workflows for durable, serviceable floors.',
        ],
        [
            'blog' => 'news',
            'slug' => 'polydeck-150-150sc-the-ultimate-waterproof-deck-system-for-long-lasting-protection',
            'title' => 'Polydeck 150: The Ultimate Waterproof Deck System for Long-Lasting Protection',
            'date' => '2025-03-11',
            'summary' => 'Waterproof deck system basics for pedestrian traffic, vehicular surfaces, and long-term protection.',
        ],
        [
            'blog' => 'news',
            'slug' => 'fp1-fusion-primer-revolutionizing-surface-preparation-for-dust-sensitive-environments',
            'title' => 'FP1 Fusion Primer: Revolutionizing Surface Preparation for Dust-Sensitive Environments',
            'date' => '2025-04-02',
            'summary' => 'Primer selection guidance for projects where dust sensitivity and surface preparation matter.',
        ],
        [
            'blog' => 'news',
            'slug' => 'epoxy-for-concrete-floors-the-ultimate-guide-to-durable-high-performance-flooring',
            'title' => 'Epoxy for Concrete Floors: The Ultimate Guide to Durable & High-Performance Flooring',
            'date' => '2026-01-03',
            'summary' => 'A broad guide to epoxy floor systems, durability, maintenance, and use cases.',
        ],
        [
            'blog' => 'news',
            'slug' => 'best-epoxy-flooring-for-warehouse-in-usa-complete-industrial-guide',
            'title' => 'Best Epoxy Flooring for Warehouse in USA: Complete Industrial Guide',
            'date' => '2026-02-10',
            'summary' => 'Warehouse flooring selection factors including traffic, abrasion, impact, cleaning, and downtime.',
        ],
        [
            'blog' => 'news',
            'slug' => 'epoxy-flooring-products-in-california',
            'title' => 'Epoxy Flooring Products in California',
            'date' => '2026-03-12',
            'summary' => 'A California-focused overview of epoxy flooring products, contractor supply, and system selection.',
        ],
        [
            'blog' => 'news',
            'slug' => 'deck-waterproofing-urethane-cement-supplier-bay-area',
            'title' => 'Deck Waterproofing & Urethane Cement Supplier Bay Area',
            'date' => '2026-04-18',
            'summary' => 'Supply support for waterproof deck coatings and urethane cement systems in the Bay Area.',
        ],
    ],
    'policies' => [
        'privacy-policy' => [
            'title' => 'Privacy Policy',
            'summary' => 'Bay Area Epoxy Wholesale uses customer information to respond to enquiries, coordinate product support, process requests, and improve the website experience.',
        ],
        'refund-policy' => [
            'title' => 'Refund Policy',
            'summary' => 'Return eligibility depends on product condition, order status, manufacturer requirements, and whether the material was special ordered or custom matched.',
        ],
        'shipping-policy' => [
            'title' => 'Shipping Policy',
            'summary' => 'Bay Area Epoxy Wholesale coordinates local pickup and project supply support from Hayward, CA, with shipping or delivery options reviewed by order and material type.',
        ],
        'terms-of-service' => [
            'title' => 'Terms of Service',
            'summary' => 'Website content is provided for product selection and quoting support. Final pricing, availability, system suitability, and order terms are confirmed directly with the Bay Area Epoxy Wholesale team.',
        ],
    ],
];
